@baseUrl = http://localhost:8080 

### Register
POST {{baseUrl}}/api/auth/employee
Content-Type: application/json

{
  "name": "Absa",
  "companyId": "bb22208b-9f33-4aa6-b642-9223c97f311d",
  "fullName": "John Doe absa",
 "email": "lekoloanenape5@gmail.com",
  "password":"Rosina^*20",
  "status": "ACTIVE",
  "role": "EMPLOYEE"
}


### login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{ 
  "email": "lekoloanenape5@gmail.com",
  "password":"Rosina^*20"
}