@baseUrl = http://localhost:8080 
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXJjeTFAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwidXNlcklkIjoiZTliMzdiZjMtYjczZi00MzFhLTkxZDctYzM2YzYzMWIyYzllIiwiaWF0IjoxNzc4MTUzNDE3LCJleHAiOjE3NzgxNTcwMTd9.RXsRR9QWneLNMqTuaCgqPUea6ytfij3_dY1si2ARRac
### Register company account
POST {{baseUrl}}/api/auth/company
Content-Type: application/json

{
  "name": "Absa",
  "fullName": "John Doe absa",
  "email": "percy1@gmail.com",
  "password":"Rosina^*20",
  "status": "ACTIVE",
  "role": "ADMIN"
}


### Register
POST {{baseUrl}}/api/auth/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Absa",
  "companyId": "bb22208b-9f33-4aa6-b642-9223c97f311d",
  "fullName": "John Doe absa",
  "email": "percy@lgmapill.com",
  "password": "Rosina^*20",
  "status": "ACTIVE",
  "role": "EMPLOYEE"
}


### login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{ 
  "email": "percy1@gmail.com",
  "password":"Rosina^*20"
}