 @baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXJjeTFAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwidXNlcklkIjoiZTliMzdiZjMtYjczZi00MzFhLTkxZDctYzM2YzYzMWIyYzllIiwiaWF0IjoxNzc4MTU5NDYwLCJleHAiOjE3NzgxNjMwNjB9.rDNYDkjk-0UVXGySsZ-ivtQ1AfntbmJXhpXEUUP9asc

###
POST {{baseUrl}}/api/projects/admin/add
Content-Type: application/json
Authorization: Bearer {{token}}

  { 
    "name": "SEO new new trategies",
    "description": "Optimizing our website for search engine search",
    "userId": "b1f1807f-4e25-4a84-8085-cf13ed7a848e"
  }

### get all projects
GET {{baseUrl}}/api/projects

### get project by id
GET {{baseUrl}}/api/projects/f10d8fd0-c2e9-4a60-b709-dc804fe1d6ce


//delete a project
###
DELETE  {{baseUrl}}/api/projects/f10d8fd0-c2e9-4a60-b709-dc804fe1d6ce


//2026-01-25